### ISSUE TITLE
Błąd rysowania trasy przy przejściu między piętrami

### ISSUE THREAD

**Issue by KarolWys93** [KNBEAN/inteligentna-mapa-szpitala#23]
Błąd występuje przy rysowaniu trasy, która ma punkt początkowy np. na parterze, punkt końcowy również ma na parterze, lecz część trasy przechodzi przez piętro. Dla aktualnego zestawu danych testowych (aktualizacja z 16.11.18) błąd występuje np. dla trasy z `place1` do `place18`.
Wyświetlane mapy na parterze:
![device-2018-11-16-224352s](https://user-images.githubusercontent.com/10165504/48649006-85718680-e9f1-11e8-8890-311f95c514f2.png)

Wyświetlanie mapy na pierwszym piętrze:
![device-2018-11-16-224416s](https://user-images.githubusercontent.com/10165504/48649037-99b58380-e9f1-11e8-8156-986b0f7f9a1f.png)

Algorytm wyszukiwania trasy działa poprawnie. Poniżej lista nodów wraz z nazwami lokacji:

ID | floor | x | y | name
-- | -- | -- | -- | --
671 | 0 | 658 | 460 | place1
77 | 0 | 658 | 431 |  
151 | 0 | 727 | 431 |  
149 | 0 | 727 | 505 |  
134 | 0 | 727 | 684 | hall0_1
135 | 0 | 727 | 707 | hall0_1
136 | 0 | 727 | 761 | hall0_1
137 | 0 | 727 | 942 | hall0_1
129 | 0 | 727 | 1005 |  
120 | 0 | 727 | 1158 |  
119 | 0 | 727 | 1199 |  
117 | 0 | 727 | 1248 |  
115 | 0 | 727 | 1330 |  
116 | 0 | 687 | 1330 | lifts01_0
520 | 1 | 681 | 1329 | lifts01_1
516 | 1 | 723 | 1329 |  
517 | 1 | 723 | 1352 |  
519 | 1 | 779 | 1352 |  
533 | 1 | 778 | 1539 |  
532 | 1 | 708 | 1539 |  
534 | 1 | 708 | 1490 | stairs1_3
102 | 0 | 708 | 1499 | stairs0_3
101 | 0 | 708 | 1537 |  
98 | 0 | 588 | 1537 |  
100 | 0 | 588 | 1499 | place18

Algorytm rysowania trasy rysuje ścieżkę na danym piętrze nie uwzględniając "przerwy" między kolejnymi nodami. Algorytm rysując ścieżkę na parterze rysuje trasę od noda 671 do 116, pomija nody 520 do 534 będące na innym piętrze i kontynuuje rysowanie od 102 do 100. Problem w tym, że narysowane jest również połączenie między nodem 116, a 102.

**Comment by KamilSwiech** [comment]
Naprawione.
Problem tworzyło iterowanie po kolejnych punktach do narysowania i dodawanie ich kolejno do ścieżki jeśli należą do piętra. Rozdzielono rysowanie na kolejne "porcje" na danym piętrze.
https://github.com/KNBEAN/inteligentna-mapa-szpitala/pull/26
